services:
  - type: web
    name: ssipmt-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://ssipmt-full-stack.vercel.app
      - key: JWT_SECRET
        value: ssipmt_super_secret_jwt_key_2024
      - key: REFRESH_SECRET
        value: ssipmt_refresh_token_secret_2024
      - key: CLOUDINARY_CLOUD_NAME
        value: de6elkznh
      - key: CLOUDINARY_API_KEY
        value: 178571164613711
      - key: CLOUDINARY_API_SECRET
        value: TREuF6sE9LCtZW6rn9ntIt_IL7o
      - key: MONGO_URI
        sync: false # User needs to paste this manually later
